
# This file is automatically generated, you probably don't want to edit this

RCBDOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "RCBDOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            trt = NULL,
            reps = 4,
            blockBy = "byRow",
            seed = 0,
            properties = TRUE,
            degfree = TRUE,
            mapGraph = FALSE,
            legend = FALSE,
            plotList = FALSE, ...) {

            super$initialize(
                package='Randomization',
                name='RCBD',
                requiresData=TRUE,
                ...)

            private$..trt <- jmvcore::OptionVariables$new(
                "trt",
                trt,
                permitted=list(
                    "factor",
                    "id"))
            private$..reps <- jmvcore::OptionInteger$new(
                "reps",
                reps,
                default=4,
                min=0)
            private$..blockBy <- jmvcore::OptionList$new(
                "blockBy",
                blockBy,
                options=list(
                    "byRow",
                    "byColumn",
                    "separate"),
                default="byRow")
            private$..seed <- jmvcore::OptionInteger$new(
                "seed",
                seed,
                default=0,
                min=0)
            private$..properties <- jmvcore::OptionBool$new(
                "properties",
                properties,
                default=TRUE)
            private$..degfree <- jmvcore::OptionBool$new(
                "degfree",
                degfree,
                default=TRUE)
            private$..mapGraph <- jmvcore::OptionBool$new(
                "mapGraph",
                mapGraph,
                default=FALSE)
            private$..legend <- jmvcore::OptionBool$new(
                "legend",
                legend,
                default=FALSE)
            private$..plotList <- jmvcore::OptionBool$new(
                "plotList",
                plotList,
                default=FALSE)

            self$.addOption(private$..trt)
            self$.addOption(private$..reps)
            self$.addOption(private$..blockBy)
            self$.addOption(private$..seed)
            self$.addOption(private$..properties)
            self$.addOption(private$..degfree)
            self$.addOption(private$..mapGraph)
            self$.addOption(private$..legend)
            self$.addOption(private$..plotList)
        }),
    active = list(
        trt = function() private$..trt$value,
        reps = function() private$..reps$value,
        blockBy = function() private$..blockBy$value,
        seed = function() private$..seed$value,
        properties = function() private$..properties$value,
        degfree = function() private$..degfree$value,
        mapGraph = function() private$..mapGraph$value,
        legend = function() private$..legend$value,
        plotList = function() private$..plotList$value),
    private = list(
        ..trt = NA,
        ..reps = NA,
        ..blockBy = NA,
        ..seed = NA,
        ..properties = NA,
        ..degfree = NA,
        ..mapGraph = NA,
        ..legend = NA,
        ..plotList = NA)
)

RCBDResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        properties = function() private$.items[["properties"]],
        degfree = function() private$.items[["degfree"]],
        plot = function() private$.items[["plot"]],
        plots = function() private$.items[["plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Randomized Complete Block Design")
            self$add(jmvcore::Table$new(
                options=options,
                name="properties",
                title="Design Properties",
                rows=1,
                columns=list(
                    list(
                        `name`="Factors", 
                        `type`="integer"),
                    list(
                        `name`="Levels", 
                        `type`="integer"),
                    list(
                        `name`="Treatments", 
                        `type`="integer"),
                    list(
                        `name`="Blocks", 
                        `type`="integer"),
                    list(
                        `name`="Plots", 
                        `type`="integer"),
                    list(
                        `name`="Seed", 
                        `type`="integer"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="degfree",
                title="Degrees of Freedom",
                rows=0,
                columns=list(
                    list(
                        `name`="Source", 
                        `type`="text"),
                    list(
                        `name`="df", 
                        `type`="integer"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot Map",
                width=600,
                height=500,
                renderFun=".plot",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="plots",
                title="Plot List",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="Plot", 
                        `type`="integer"),
                    list(
                        `name`="Block", 
                        `type`="integer"),
                    list(
                        `name`="Column", 
                        `type`="integer"),
                    list(
                        `name`="Row", 
                        `type`="integer"),
                    list(
                        `name`="Treatment", 
                        `type`="text"))))}))

RCBDBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "RCBDBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'Randomization',
                name = 'RCBD',
                version = c(0,3,0),
                options = options,
                results = RCBDResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Randomized Complete Block Design
#'
#' 
#' @param data .
#' @param trt .
#' @param reps .
#' @param blockBy .
#' @param seed .
#' @param properties .
#' @param degfree .
#' @param mapGraph .
#' @param legend .
#' @param plotList .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$properties} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$degfree} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$plots} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$properties$asDF}
#'
#' \code{as.data.frame(results$properties)}
#'
#' @export
RCBD <- function(
    data,
    trt,
    reps = 4,
    blockBy = "byRow",
    seed = 0,
    properties = TRUE,
    degfree = TRUE,
    mapGraph = FALSE,
    legend = FALSE,
    plotList = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('RCBD requires jmvcore to be installed (restart may be required)')

    if ( ! missing(trt)) trt <- jmvcore::resolveQuo(jmvcore::enquo(trt))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(trt), trt, NULL))


    options <- RCBDOptions$new(
        trt = trt,
        reps = reps,
        blockBy = blockBy,
        seed = seed,
        properties = properties,
        degfree = degfree,
        mapGraph = mapGraph,
        legend = legend,
        plotList = plotList)

    analysis <- RCBDClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
